#!/usr/bin/env bash
# ============================================
# setup-dns.sh — Print required DNS records
# ============================================
# Run this to see all DNS records you need to add.
# magicqc.com → Namecheap
# robionix.com → GoDaddy (via Cloudflare)

set -euo pipefail

VPS_IP="121.52.149.158"
DOMAIN="magicqc.com"

cat <<EOF
╔══════════════════════════════════════════════════════════════╗
║           DNS Records for ${DOMAIN}                          ║
║           Add these at Namecheap DNS Management              ║
╚══════════════════════════════════════════════════════════════╝

──── REQUIRED ────

1. MX Record (receive mail)
   Type: MX
   Host: @
   Value: mail.${DOMAIN}
   Priority: 10

2. A Record — mail server
   Type: A
   Host: mail
   Value: ${VPS_IP}

3. A Record — JMAP API
   Type: A
   Host: jmap
   Value: ${VPS_IP}

4. A Record — Admin panel
   Type: A
   Host: admin
   Value: ${VPS_IP}

5. A Record — Autoconfig
   Type: A
   Host: autoconfig
   Value: ${VPS_IP}

6. A Record — MTA-STS
   Type: A
   Host: mta-sts
   Value: ${VPS_IP}

──── EMAIL AUTHENTICATION ────

7. SPF Record (who can send mail for this domain)
   Type: TXT
   Host: @
   Value: v=spf1 a mx ip4:${VPS_IP} -all

8. DKIM Record (will be generated by Stalwart)
   Type: TXT
   Host: 202501._domainkey
   Value: (get from Stalwart admin → Settings → DKIM)

9. DMARC Record (email authentication policy)
   Type: TXT
   Host: _dmarc
   Value: v=DMARC1; p=reject; rua=mailto:postmaster@${DOMAIN}; ruf=mailto:postmaster@${DOMAIN}; adkim=s; aspf=s; pct=100

──── MTA-STS ────

10. MTA-STS TXT Record
    Type: TXT
    Host: _mta-sts
    Value: v=STSv1; id=20250101

──── SMTP TLS Reporting ────

11. TLSRPT Record
    Type: TXT
    Host: _smtp._tls
    Value: v=TLSRPTv1; rua=mailto:postmaster@${DOMAIN}

──── OPTIONAL: DANE (if DNSSEC available) ────

12. TLSA Record (for DANE — only if Namecheap supports DNSSEC)
    Type: TLSA
    Host: _25._tcp.mail
    Value: (generated from TLS certificate)

═══════════════════════════════════════════════════════════════

VERIFICATION COMMANDS (run after adding records):

  # Check MX record
  dig MX ${DOMAIN} +short

  # Check SPF
  dig TXT ${DOMAIN} +short

  # Check DMARC
  dig TXT _dmarc.${DOMAIN} +short

  # Check DKIM (after Stalwart generates it)
  dig TXT 202501._domainkey.${DOMAIN} +short

  # Test email deliverability
  # → https://www.mail-tester.com
  # → https://mxtoolbox.com/SuperTool.aspx

═══════════════════════════════════════════════════════════════
EOF
